name             'check_mk'
maintainer       'Fewbytes'
maintainer_email 'chef@fewbytes.com'
license          'Apache-2.0'
description      'Installs/Configures Check_MK'
version          '1.2.0'

depends 'apache2'
depends 'php'
depends 'xinetd'
depends 'source'
depends 'ark'
depends 'sudo'

supports 'ubuntu', '>= 10.04'
supports 'debian', '>= 6.0.0'
supports 'redhat', '~= 7.5'
supports 'centos', '~> 7.5'
